import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          "  bg-gradient-to-b from-gray-400 to-white min-h-[100vh] flex justify-between  flex-col"
        }
      >
        <Toaster/>
        <Navbar />
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
